// CONSTANTES PARA CARREGAR PRODUTOS
export const CARREGA_PRODUTOS = 'CARREGA_PRODUTOS'
export const CARREGA_PRODUTOS_SUCESS = 'CARREGA_PRODUTOS_SUCESS'
export const CARREGA_PRODUTOS_FAIL = 'CARREGA_PRODUTOS_FAIL'
export const ADD_PRODUTOS = 'ADD_PRODUTOS'
export const CARREGA_TOKEN = 'CARREGA_TOKEN'